#!/usr/bin/env bash
# to ping an IP address passed as an argument
# the command ping uses ICMP to make sure that a network device remains online or to troubleshoot issues on the network.
if [ -z "$1" ] 
then 
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi